import { describe, expect, it } from "vitest";
import { parseSQLTables } from "../parser/sql";

// 跨方言（SQL Server / Oracle / PostgreSQL / SQLite / MySQL）的 CREATE TABLE 覆盖。
// 验证基于词法分析的解析器能稳定提取表名 / 列名 / 类型 / 主键 / 外键，而不被各方言
// 特有的修饰（IDENTITY(1,1)、GENERATED ... AS IDENTITY、SERIAL、数组、UNSIGNED 等）干扰。

describe("parseSQLTables — 方言覆盖", () => {
  const typeMap = (sql: string, idx = 0) =>
    Object.fromEntries(parseSQLTables(sql).tables[idx].columns.map((c) => [c.name, c.type]));

  it("SQL Server：IDENTITY(1,1) / NVARCHAR(MAX) / [schema].[tbl] / PK CLUSTERED", () => {
    const r = parseSQLTables(`
      CREATE TABLE [dbo].[Account] (
        [Id] INT IDENTITY(1,1) NOT NULL,
        [Name] NVARCHAR(MAX) NULL,
        [Guid] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
        [Ver] ROWVERSION,
        CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED ([Id] ASC)
      ) ON [PRIMARY];
    `);
    const t = r.tables[0];
    expect(t.name).toBe("dbo.Account");
    expect(t.columns.map((c) => c.name)).toEqual(["Id", "Name", "Guid", "Ver"]);
    expect(t.primaryKeys).toEqual(["Id"]);
    const types = typeMap(`
      CREATE TABLE [dbo].[Account] (
        [Id] INT IDENTITY(1,1) NOT NULL,
        [Name] NVARCHAR(MAX) NULL,
        CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED ([Id] ASC)
      );
    `);
    expect(types.Id).toBe("INT");
    expect(types.Name).toBe("NVARCHAR(MAX)");
  });

  it("Oracle：VARCHAR2(100 CHAR) / NUMBER(10,2) / GENERATED ALWAYS AS IDENTITY", () => {
    const r = parseSQLTables(`
      CREATE TABLE employees (
        emp_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100 CHAR) NOT NULL,
        salary NUMBER(10,2) DEFAULT 0,
        hired DATE DEFAULT SYSDATE,
        doc CLOB
      );
    `);
    const t = r.tables[0];
    expect(t.primaryKeys).toEqual(["emp_id"]);
    const types = Object.fromEntries(t.columns.map((c) => [c.name, c.type]));
    expect(types.emp_id).toBe("NUMBER");
    expect(types.name).toBe("VARCHAR2(100 CHAR)");
    expect(types.salary).toBe("NUMBER(10,2)");
  });

  it("Oracle：GENERATED BY DEFAULT AS IDENTITY + schema 限定 FK", () => {
    const r = parseSQLTables(`
      CREATE TABLE hr.dept (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50)
      );
      CREATE TABLE hr.emp (
        id NUMBER PRIMARY KEY,
        dept_id NUMBER,
        CONSTRAINT fk_emp_dept FOREIGN KEY (dept_id) REFERENCES hr.dept (id)
      );
    `);
    expect(r.tables.map((t) => t.name)).toEqual(["hr.dept", "hr.emp"]);
    expect(r.relationships).toEqual([
      {
        from: "hr.emp",
        to: "hr.dept",
        label: "dept_id",
        fromCardinality: "N",
        toCardinality: "1",
      },
    ]);
  });

  it("PostgreSQL：BIGSERIAL / jsonb / text[] / numeric()[] / timestamptz / inet", () => {
    const sql = `
      CREATE TABLE public.events (
        id BIGSERIAL PRIMARY KEY,
        uid UUID NOT NULL DEFAULT gen_random_uuid(),
        payload JSONB NOT NULL DEFAULT '{}'::jsonb,
        tags TEXT[] DEFAULT '{}',
        amounts NUMERIC(12,2)[],
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        ip INET
      );
    `;
    const r = parseSQLTables(sql);
    const t = r.tables[0];
    expect(t.name).toBe("public.events");
    expect(t.columns.map((c) => c.name)).toEqual([
      "id",
      "uid",
      "payload",
      "tags",
      "amounts",
      "created_at",
      "ip",
    ]);
    expect(t.primaryKeys).toEqual(["id"]);
    const types = typeMap(sql);
    expect(types.payload).toBe("JSONB");
    expect(types.tags).toBe("TEXT[]");
    expect(types.amounts).toBe("NUMERIC(12,2)[]");
  });

  it("PostgreSQL：GENERATED ALWAYS AS IDENTITY 主键", () => {
    const r = parseSQLTables(`
      CREATE TABLE t (
        id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        label TEXT
      );
    `);
    expect(r.tables[0].primaryKeys).toEqual(["id"]);
    expect(r.tables[0].columns[0].type).toBe("INT");
  });

  it("SQLite：INTEGER PRIMARY KEY AUTOINCREMENT / WITHOUT ROWID / 方括号保留字列名", () => {
    const r = parseSQLTables(`
      CREATE TABLE [main].[kv] (
        [key] TEXT NOT NULL,
        [val] BLOB,
        rowid INTEGER PRIMARY KEY AUTOINCREMENT
      ) WITHOUT ROWID;
    `);
    const t = r.tables[0];
    expect(t.name).toBe("main.kv");
    expect(t.columns.map((c) => c.name)).toEqual(["key", "val", "rowid"]);
    expect(t.primaryKeys).toEqual(["rowid"]);
  });

  it("MySQL：UNSIGNED ZEROFILL / ENUM / ON UPDATE CURRENT_TIMESTAMP", () => {
    const sql = `
      CREATE TABLE m (
        id BIGINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
        ratio DECIMAL(5,2) UNSIGNED,
        state ENUM('a','b') NOT NULL DEFAULT 'a',
        updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (id)
      ) ENGINE=InnoDB;
    `;
    const r = parseSQLTables(sql);
    expect(r.tables[0].primaryKeys).toEqual(["id"]);
    const types = typeMap(sql);
    expect(types.id).toBe("BIGINT UNSIGNED ZEROFILL");
    expect(types.ratio).toBe("DECIMAL(5,2) UNSIGNED");
    expect(types.state).toBe("ENUM('a','b')");
    expect(types.updated).toBe("TIMESTAMP");
  });
});
