// Bundles the headless engine (engine/cli.ts + the app's parser/builder/layout)
// into one self-contained Node ESM file: scripts/sql2er-agent.mjs.
// Run from the repo root:  node skills/sql2er/scripts/build.mjs
import * as esbuild from "esbuild";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../../../"); // scripts -> sql2er -> skills -> repo root
const src = resolve(root, "src");
const generatedDir = resolve(here, ".generated");
const embeddedJs = resolve(generatedDir, "embedded.js");
const embeddedCss = resolve(generatedDir, "embedded.css");
const embeddedAssetsModule = resolve(here, "engine/embedded-assets.generated.ts");
const agentOut = resolve(here, "sql2er-agent.mjs");

rmSync(generatedDir, { recursive: true, force: true });
mkdirSync(generatedDir, { recursive: true });

await esbuild.build({
  entryPoints: [resolve(root, "src/embedded.tsx")],
  outfile: embeddedJs,
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  minify: true,
  jsx: "automatic",
  define: {
    "process.env.NODE_ENV": '"production"',
  },
  logLevel: "info",
});

writeFileSync(
  embeddedAssetsModule,
  [
    "// Generated by skills/sql2er/scripts/build.mjs. Do not edit by hand.",
    `export const EMBEDDED_APP_JS = ${JSON.stringify(readFileSync(embeddedJs, "utf8"))};`,
    `export const EMBEDDED_APP_CSS = ${JSON.stringify(
      existsSync(embeddedCss) ? readFileSync(embeddedCss, "utf8") : "",
    )};`,
    "",
  ].join("\n"),
  "utf8",
);

await esbuild.build({
  entryPoints: [resolve(here, "engine/cli.ts")],
  outfile: agentOut,
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node18",
  // The engine imports the app's pure modules as @app/*; map that to ../src.
  alias: { "@app": src },
  legalComments: "none",
  logLevel: "info",
});

writeFileSync(agentOut, readFileSync(agentOut, "utf8").replace(/[ \t]+$/gm, ""), "utf8");

process.stdout.write("built sql2er-agent.mjs\n");
